### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by kirbysayshi** [jcartledge/vintage-sublime-surround#1]
Sorry for the lack of descriptive issue title.

I installed through package control.

I have text:

```
'this is text'
```

If my cursor is on the `t` in `text`, and I press `cs'"`, I would expect the `'` to change to `"`. Instead, nothing happens, and in the status bar I get a message `COMMAND MODE, 0 selection regions`.

Am I doing this wrong? Perhaps I'm misinterpreting the functionality of this plugin?

Thanks for making it though!

**Comment by kirbysayshi** [comment]
Well this is embarrassing. I didn't realize this plugin depended on sublime-surround. It's working now!

**Comment by jcartledge** [comment]
Hi Andrew. 

Have you installed the sublime-surround package as well? That provides the surround functionality, this package is just Vintage mappings for it. 

Check in package control if you have that installed. If that's not it, please let me know.

**Comment by jcartledge** [comment]
Glad to hear!
